-- 修改表结构(索引、约束)

-- 增加表字段
ALTER TABLE ROOM ADD DATETIME Date; -- 增加 datetime 字段，类型为 date
ALTER TABLE ROOM ADD TITLE VARCHAR(20); 

-- 删除表字段
ALTER TABLE ROOM DROP COLUMN TITLE;

-- 修改表字段数据类型
ALTER TABLE ROOM ALTER COLUMN RoomId varchar(45); -- SQL server
-- ALTER TABLE ROOM MODIFY COLUMN RoomId varchar(45);  -- mysql / oracle

-- 修改约束条件
-- 唯一值约束
ALTER TABLE ROOM ADD UNIQUE (RoomId);
ALTER TABLE ROOM ADD CONSTRAINT un_name UNIQUE (RoomId, Intro); -- 可以对约束命名
-- ALTER TABLE ROOM DROP INDEX un_name;   -- mysql
ALTER TABLE ROOM DROP CONSTRAINT un_name;

-- 主键
ALTER TABLE ROOM ADD PRIMARY KEY (RoomId);
ALTER TABLE ROOM ADD CONSTRAINT pk_name PRIMARY KEY (RoomId, Area);
-- ALTER TABLE ROOM DROP PRIMARY KEY;   -- mysql
ALTER TABLE ROOM DROP CONSTRAINT pk_name;

-- 外键
ALTER TABLE FURNITURE ADD FOREIGN KEY (room_id) REFERENCES ROOM(RoomId);  -- 家具的表中将房间的id设为与房间表相关的外键
ALTER TABLE FURNITURE ADD CONSTRAINT fk_name FOREIGN KEY (room_id) REFERENCES ROOM(RoomId);
-- ALTER TABLE FURNITURE DROP FOREIGN KEY fk_name;  -- mysql
ALTER TABLE FURNITURE DROP CONSTRAINT fk_name;

-- 条件取值
ALTER TABLE ROOM ADD CHECK (Area > 0);
ALTER TABLE ROOM ADD CONSTRAINT chk_name CHECK (RoomId>0 AND Area>'0');
-- ALTER TABLE ROOM DROP CHECK chk_name; -- mysql
ALTER TABLE ROOM DROP CONSTRAINT chk_name;

-- 默认值
ALTER TABLE ROOM ADD CONSTRAINT de_name DEFAULT 'white' for Color;
-- ALTER TABLE ROOM ALTER Color SET DEFAULT 'white'; -- mysql
-- ALTER TABLE ROOM MODIFY Color DEFAULT 'white';  -- oracle
-- ALTER TABLE ROOM ALTER Color DROP DEFAULT;  -- mysql
-- ALTER TABLE ROOM ALTER COLUMN Color DROP DEFAULT; -- common

-- 自增
-- ALTER TABLE ROOM CHANGE RoomId RoomId INT( 11 ) NOT NULL AUTO_INCREMENT;  -- mysql
